services:
  - type: web
    name: nl-flowchart-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
